@host = http://localhost:8000
@api = /api/v1
# update this to the actual file.id from the upload
@id = f81bd3bb-8b9c-4c93-9234-ff036e0ca648

### Upload a file to MinIO (uses local test file)
# @name upload
POST {{host}}{{api}}/files/upload
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< ./backend/test/test.txt
--MyBoundary--


### Get a presigned download URL for the uploaded object
GET {{host}}{{api}}/files/presign?id={{id}}&expires=60

### Redirect directly to a presigned URL (good for <img src=...>)
GET {{host}}{{api}}/files/presign-redirect?id={{id}}&expires=60

### Delete the uploaded object
DELETE {{host}}{{api}}/files/?id={{id}}


### Upload an image to MinIO
# @name upload_image
POST {{host}}{{api}}/files/upload?folder=images
Content-Type: multipart/form-data; boundary=ImgBoundary

--ImgBoundary
Content-Disposition: form-data; name="file"; filename="sample.jpeg"
Content-Type: image/jpeg

< ./backend/test/sample.jpeg
--ImgBoundary--