"""remove sha256 from file

Revision ID: 28d3a60f6d2a
Revises: 99e09155289c
Create Date: 2025-09-20 17:34:41.087701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d3a60f6d2a'
down_revision: Union[str, Sequence[str], None] = '99e09155289c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_sha256'), table_name='files')
    op.drop_column('files', 'sha256')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('sha256', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_files_sha256'), 'files', ['sha256'], unique=True)
    # ### end Alembic commands ###
