"""remove object_key column from files

Revision ID: 3bfd86f21110
Revises: 28d3a60f6d2a
Create Date: 2025-09-20 19:25:19.610983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfd86f21110'
down_revision: Union[str, Sequence[str], None] = '28d3a60f6d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'object_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('object_key', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
