"""Initial schema with real tables

Revision ID: 99e09155289c
Revises: 10a995db52d0
Create Date: 2025-09-20 13:16:08.197649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e09155289c'
down_revision: Union[str, Sequence[str], None] = '10a995db52d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('object_key', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'object_key')
    # ### end Alembic commands ###
